ECOM.Web/ViewModels/FormaPagtoViewModels.cs
namespace ECOM.Web.ViewModels
{
    public class FormaPagtoViewModels
    {
        public string Tipo { get; set; }
        public int Id { get; set; }
    }
}

ECOM.Web/Controllers/FormaPagtoController.cs
using AutoMapper;
using ECOM.Application.Entities;
using ECOM.Domain.Entities;
using ECOM.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ECOM.Web.Controllers
{
    public class FormaPagtoController : Controller
    {
        private readonly FormaPagtoApp _formaPagtoApp;

        public FormaPagtoController(FormaPagtoApp formaPagtoApp)
        {
            _formaPagtoApp = formaPagtoApp;
        }

        public ActionResult Index()
        {
            List<FormaPagtoViewModels> formaPagtosVW = Mapper.Map<IEnumerable<FormaPagto>, IEnumerable<FormaPagtoViewModels>>(_formaPagtoApp.GetAll()).ToList();

            if (Request.IsAjaxRequest())
                return PartialView(formaPagtosVW);

            return View(formaPagtosVW);
        }

        public ActionResult CreateEdit(int? id)
        {
            FormaPagtoViewModels fPagtoVW;
            if (id != null)
                fPagtoVW = Mapper.Map<FormaPagto, FormaPagtoViewModels>(_formaPagtoApp.GetEntityById(id.Value));
            else
                fPagtoVW = new FormaPagtoViewModels();

            if (Request.IsAjaxRequest())
                return PartialView(fPagtoVW);
            return View(fPagtoVW);
        }
        
        [HttpPost]
        public ActionResult CreateEdit(FormaPagtoViewModels fPagtoVW)
        {
            if(ModelState.IsValid)
            {
                FormaPagto formaPagto = Mapper.Map<FormaPagtoViewModels, FormaPagto>(fPagtoVW);
                if (fPagtoVW.Id == 0)
                    _formaPagtoApp.AddEntity(formaPagto);
                else
                    _formaPagtoApp.UpdateEntity(formaPagto);
                return RedirectToAction("Index");
            }
            return View(fPagtoVW);
        }

        public ActionResult Delete(int id)
        {
            _formaPagtoApp.DeleteEntity(_formaPagtoApp.GetEntityById(id));

            return Json(new { status = "deletado com sucesso", JsonRequestBehavior.AllowGet });
        }
    }
}

ECOM.Web/Views/FormaPagto/CreateEdit.cshtml
@model ECOM.Web.ViewModels.FormaPagtoViewModels
@{
    ViewBag.Title = Model.Id == 0 ? "Create" : "Edit";
}
<div class="row wrapper border-bottom white-bg page-heading animated fadeInDown">
    <div class="col-sm-4">
        <h2>@ViewBag.Title </h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
</div>

@using (Ajax.BeginForm("CreateEdit", "FormaPagto", new AjaxOptions
{
    OnSuccess = "OFrame.Ecom.Form.Success(data, this)",
}, new { id = "form-business", role = "form",  title = ViewBag.Title, urlBack = Url.Action("Index") }))
{
    <div class="wrapper wrapper-content animated fadeInDown">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><i class="fa fa-pencil-square-o"></i> @ViewBag.Title</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="fullscreen-link">
                                <i class="fa fa-expand"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-bars"></i>
                            </a>
                           
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-4 has-warning">
                                <div class="form-group">
                                    <label>@Html.LabelFor(model => model.Tipo, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.Tipo, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Tipo)
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <button class="btn btn-success" type="submit" accesskey="s">
                                    <i class="fa fa-save"></i>
                                    <span class="bold">SALVAR</span>
                                </button>
                                <button class="btn btn-outline btn-danger" accesskey="c" type="button" onclick="location.href='@Url.Action("Index", "FormaPagto")'">
                                    <span class="bold">CANCELAR</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<script type="text/javascript">

    $(document).ready(function () {

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
        });

    });

</script>

ECOM.Web/Views/FormaPagto/Index.cshtml
@model List<ECOM.Web.ViewModels.FormaPagtoViewModels>

<div class="row wrapper border-bottom white-bg page-heading animated fadeInDown">
    <div class="col-sm-4">
        <h2>Cadastro Forma Pagamento </h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Forma Pagamento</strong>
            </li>
        </ol>
    </div>
</div>

@Html.Partial("_Result")

ECOM.Web/Views/FormaPagto/_Result.cshtml
@model List<ECOM.Web.ViewModels.FormaPagtoViewModels>
<div class="wrapper wrapper-content animated fadeInDown">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>
                        <i class="fa fa-list"></i>
                        Forma de Pagamento
                    </h5>
                    <div class="ibox-tools">
                        <button type="button" class="btn btn-success btn-xs" title="Novo" onclick="location.href='@Url.Action("CreateEdit", "FormaPagto")'"><i class="fa fa-plus"></i> Novo</button>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="fullscreen-link">
                            <i class="fa fa-expand"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table id="table-fPagto" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="width-20">Id</th>
                                <th>Forma Pagamento</th>
                                <th class="no-sort width-80">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Tipo</td>
                                    <td class="center">
                                        <div class="btn-group">
                                            <a class="btn btn-white btn-xs" accesskey="e" title="Edit" href="@Url.Action("CreateEdit" , "FormaPagto" , new { id = item.Id})"><i class="fa fa-pencil"></i></a>
                                            <button class="btn btn-white btn-xs" accesskey="d" title="Delete" type="button" onclick="Delete('@item.Id')"><i class="fa fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        OFrame.ECOM.Table.GetDefault("#table-fPagto");
    });

      function Delete(id) {
        var param = { id: id }

        OFrame.ECOM.ConfirmMessage("warning", "@Html.Raw("Dados Serão deletados")", "@Html.Raw("Confirma exclusão")",

            function () {

                $.ajax({
                    type: "Post",
                    contentType: "application/json; charset=utf-8",
                    url: "FormaPagto/Delete",
                    data: JSON.stringify(param),
                    dataType: "json",
                    success: function (data) {
                        OFrame.ECOM.ShowMessage("success", "@Html.Raw("Sucesso")",
                            "@Html.Raw("Deletado")", function () {
                                OFrame.ECOM.OpenAjaxUrl("@Url.Action("Index")");
                            });
                    }
                });
            }
            );
    }

</script>