ECOM.Web/ViewModels/FornecedorViewModels.cs
using ECOM.Domain.Entities;
using System.Collections.Generic;

namespace ECOM.Web.ViewModels
{
    public class FornecedorViewModels
    {
        public FornecedorViewModels()
        {
            this.Produtos = new List<Produto>();
        }
        public int Id { get; set; }
        public string RazaoSocial { get; set; }
        public string Nomefantasia { get; set; }
        public string CNPJ { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string EnderecoComercial { get; set; }
        public IEnumerable<Produto> Produtos { get; set; }
        
    }
}

ECOM.Web/Controllers/FornecedorController.cs
using AutoMapper;
using ECOM.Application.Entities;
using ECOM.Domain.Entities;
using ECOM.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ECOM.Web.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly FornecedorApp _fornecedorApp;
        private readonly ProdutoApp _produtoApp;
        public FornecedorController(FornecedorApp fornecedorApp , ProdutoApp produtoApp)
        {
            _fornecedorApp = fornecedorApp;
            _produtoApp = produtoApp;
        }
        public ActionResult Index()
        {
            List<FornecedorViewModels> fornecedorVW = Mapper.Map< IEnumerable<Fornecedores>, IEnumerable<FornecedorViewModels>>(_fornecedorApp.GetAll()).ToList();
            if (Request.IsAjaxRequest())
                return PartialView(fornecedorVW);
            return View(fornecedorVW);
        }

        public ActionResult CreateEdit(int?  id)
        {
            FornecedorViewModels fornecedor;
            if (id != null)
            {
                fornecedor = Mapper.Map<Fornecedores, FornecedorViewModels>(_fornecedorApp.GetEntityById(id.Value));
                fornecedor.Produtos = _produtoApp.GetAll().Where(x => x.CategoriaProdutoId == id.Value).ToList();
                IEnumerable<SelectListItem> produtoList = fornecedor.Produtos.Select(x =>
                                                            new SelectListItem()
                                                            {
                                                                Text = x.Nome,
                                                                Value = x.Id.ToString()
                                                            });
                ViewBag.Produtos = produtoList;
            }
            else
            {
                fornecedor = new FornecedorViewModels();
            }
            if (Request.IsAjaxRequest())
                return PartialView(fornecedor);

            return View(fornecedor);
        }

        [HttpPost]
        public ActionResult CreateEdit(FornecedorViewModels fornecedorViewModels)
        {
            if(ModelState.IsValid)
            {
                Fornecedores fornecedor = Mapper.Map<FornecedorViewModels, Fornecedores>(fornecedorViewModels);
                if (fornecedorViewModels.Id == 0)
                    _fornecedorApp.AddEntity(fornecedor);
                else
                    _fornecedorApp.UpdateEntity(fornecedor);

                return RedirectToAction("Index");
            }

            return View(fornecedorViewModels);
        }

        public ActionResult Delete(int id)
        {
            _fornecedorApp.DeleteEntity(_fornecedorApp.GetEntityById(id));

            return Json(new { status = "deletado com sucesso", JsonRequestBehavior.AllowGet });
        }
    }
}

ECOM.Web/Views/Fornecedor/CreateEdit.cshtml
@model ECOM.Web.ViewModels.FornecedorViewModels
@{
    ViewBag.Title = Model.Id == 0 ? "Create" : "Edit";
}
<div class="row wrapper border-bottom white-bg page-heading animated fadeInDown">
    <div class="col-sm-4">
        <h2>@ViewBag.Title </h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
</div>

@using (Ajax.BeginForm("CreateEdit", "Fornecedor", new AjaxOptions
{
    OnSuccess = "OFrame.Ecom.Form.Success(data, this)",
}, new { id = "form-business", role = "form", title = ViewBag.Title, urlBack = Url.Action("Index") }))
{
    <div class="wrapper wrapper-content animated fadeInDown">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><i class="fa fa-pencil-square-o"></i> @ViewBag.Title</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="fullscreen-link">
                                <i class="fa fa-expand"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-bars"></i>
                            </a>

                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-4 has-warning">
                                <div class="form-group">
                                    <label>@Html.LabelFor(model => model.RazaoSocial, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.RazaoSocial, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.RazaoSocial)
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group has-warning">
                                    <label>@Html.LabelFor(model => model.Nomefantasia, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.Nomefantasia, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Nomefantasia)
                                </div>
                            </div>
                            <div class="col-sm-4 has-warning">
                                <div class="form-group">
                                    <label>@Html.LabelFor(model => model.CNPJ, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.CNPJ, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CNPJ)
                                </div>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-sm-4 has-warning">
                                <div class="form-group">
                                    <label>@Html.LabelFor(model => model.Telefone, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Telefone)
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group has-warning">
                                    <label>@Html.LabelFor(model => model.Celular, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.Celular, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Celular)
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group has-warning">
                                    <label>@Html.LabelFor(model => model.EnderecoComercial, new { @class = "font-normal" })</label>
                                    @Html.TextBoxFor(model => model.EnderecoComercial, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EnderecoComercial)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label>@Html.Label("Produtos associados", new { @class = "font-normal" })</label>
                                    @if (Model.Id != 0)
                                    {
                                        @Html.DropDownList("produtosList", (IEnumerable<SelectListItem>)ViewBag.Produtos, new { id = "drop-produto", @class = "form-control", multiple = "multiple" })
                                    }
                                    else
                                    {
                                        <select id="drop-produto"> <option></option> </select>
                                    }
                                    </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <button class="btn btn-success" type="submit" accesskey="s">
                                    <i class="fa fa-save"></i>
                                    <span class="bold">SALVAR</span>
                                </button>
                                <button class="btn btn-outline btn-danger" accesskey="c" type="button" onclick="location.href='@Url.Action("Index", "Fornecedor")'">
                                    <span class="bold">CANCELAR</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<script type="text/javascript">

    $(document).ready(function () {
        loadItens();
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
        });

    });


    function loadItens() {
        $('#drop-produto').select2({ width: '100%' });
        var valores = document.getElementById('drop-produto').options.length;
        var arr = [];
        for (var i = 1; i <= valores; i++) {
            arr.push(i.toString());
        }
        $('#drop-produto').val(arr).trigger('change');
        $('#drop-produto').trigger('change');
    }

</script>

ECOM.Web/Views/Fornecedor/Index.cshtml
@model List<ECOM.Web.ViewModels.FornecedorViewModels>

<div class="row wrapper border-bottom white-bg page-heading animated fadeInDown">
    <div class="col-sm-4">
        <h2>Cadastro Fornecedor </h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Fornecedor</strong>
            </li>
        </ol>
    </div>
</div>

@Html.Partial("_Result")

ECOM.Web/Views/Fornecedor/_Result.cshtml
@model List<ECOM.Web.ViewModels.FornecedorViewModels>
<div class="wrapper wrapper-content animated fadeInDown">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>
                        <i class="fa fa-list"></i>
                        Fornecedor
                    </h5>
                    <div class="ibox-tools">
                        <button type="button" class="btn btn-success btn-xs" title="Novo" onclick="location.href='@Url.Action("CreateEdit", "Fornecedor")'"><i class="fa fa-plus"></i> Novo</button>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="fullscreen-link">
                            <i class="fa fa-expand"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table id="table-for" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="width-20">Id</th>
                                <th>Razão Social</th>
                                <th>Nome fantasia</th>
                                <th>CNPJ</th>
                                <th>Telefone</th>
                                <th>Celular</th>
                                <th>Endereço Comercial</th>
                                <th class="no-sort width-80">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.RazaoSocial</td>
                                    <td>@item.Nomefantasia</td>
                                    <td>@item.CNPJ</td>
                                    <td>@item.Telefone</td>
                                    <td>@item.Celular</td>
                                    <td>@item.EnderecoComercial</td>
                                    <td class="center">
                                        <div class="btn-group">
                                            <a class="btn btn-white btn-xs" accesskey="e" title="Edit" href="@Url.Action("CreateEdit" , "Fornecedor" , new { id = item.Id})"><i class="fa fa-pencil"></i></a>
                                            <button class="btn btn-white btn-xs" accesskey="d" title="Delete" type="button" onclick="Delete('@item.Id')"><i class="fa fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        OFrame.ECOM.Table.GetDefault("#table-for");
    });

      function Delete(id) {
        var param = { id: id }

        OFrame.ECOM.ConfirmMessage("warning", "@Html.Raw("Dados Serão deletados")", "@Html.Raw("Confirma exclusão")",

            function () {

                $.ajax({
                    type: "Post",
                    contentType: "application/json; charset=utf-8",
                    url: "Fornecedor/Delete",
                    data: JSON.stringify(param),
                    dataType: "json",
                    success: function (data) {
                        OFrame.ECOM.ShowMessage("success", "@Html.Raw("Sucesso")",
                            "@Html.Raw("Deletado")", function () {
                                OFrame.ECOM.OpenAjaxUrl("@Url.Action("Index")");
                            });
                    }
                });
            }
            );
    }

</script>