ECOM.Web/ViewModels/ProdutoViewModel.cs
using ECOM.Domain.Entities;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace ECOM.Web.ViewModels
{
    public class ProdutoViewModel
    {
        public ProdutoViewModel()
        {
            Categorias = new List<SelectListItem>();
            Fornecedores = new List<SelectListItem>();

            Imagem1 = new byte[0];
            Imagem2 = new byte[0];
            Imagem3 = new byte[0];
            Imagem4 = new byte[0];

            
        }
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public bool Disponivel { get; set; }
        public byte[] Imagem1 { get; set; }
        public byte[] Imagem2 { get; set; }
        public byte[] Imagem3 { get; set; }
        public byte[] Imagem4 { get; set; }
        public string ImgVisual1 { get; set; }
        public string ImgVisual2 { get; set; }
        public string ImgVisual3 { get; set; }
        public string ImgVisual4 { get; set; }
        public int CategoriaProdutoId { get; set; }
        public virtual CategoriaProduto CategoriaProduto { get; set; }
        public int FornecedorId { get; set; }
        public virtual Fornecedores Fornecedor { get; set; }
        public IEnumerable<SelectListItem> Categorias { get; set; }
        public IEnumerable<SelectListItem> Fornecedores { get; set; }

        public decimal Preco { get; set; }
        
    }
}

ECOM.Web/Controllers/ProdutoController.cs
using AutoMapper;
using ECOM.Application.Entities;
using ECOM.Domain.Entities;
using ECOM.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECOM.Web.Helpers;

namespace ECOM.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ProdutoApp _produtoApp;
        private readonly FornecedorApp _fornecedorApp;
        private readonly CategoriaProdutoApp _categoriaApp;


        public ProdutoController(ProdutoApp produtoApp , FornecedorApp fornecedorApp , CategoriaProdutoApp categoriaProdutoApp)
        {
            _produtoApp = produtoApp;
            _fornecedorApp = fornecedorApp;
            _categoriaApp = categoriaProdutoApp;
        }

        public ActionResult Index()
        {
            //IEnumerable<Produto> products = _produtoApp.GetAll("CategoriaProduto", "Fornecedor");
            //List<ProdutoViewModel> produtos = new List<ProdutoViewModel>();
            //foreach (var item in products)
            //{
            //    produtos.Add(Mapper.Map<Produto, ProdutoViewModel>(item));
            //}

            List<ProdutoViewModel> produtos = Mapper.Map<IEnumerable<Produto>, IEnumerable<ProdutoViewModel>>(_produtoApp.GetAll("CategoriaProduto", "Fornecedor")).ToList();


            if (Request.IsAjaxRequest())
                return PartialView(produtos);
            return View(produtos);
        }

        public ActionResult CreateEdit(int? id)
        {
            ProdutoViewModel produtoVW = new ProdutoViewModel();
           
            if (id != null)
            {
                produtoVW = Mapper.Map<Produto, ProdutoViewModel>(_produtoApp.GetEntityById(id.Value));
                produtoVW.ImgVisual1 = UtilHelper.RetornaFromByteToImageString(produtoVW.Imagem1);
                produtoVW.ImgVisual2 = UtilHelper.RetornaFromByteToImageString(produtoVW.Imagem2);
                produtoVW.ImgVisual3 = UtilHelper.RetornaFromByteToImageString(produtoVW.Imagem3);
                produtoVW.ImgVisual4 = UtilHelper.RetornaFromByteToImageString(produtoVW.Imagem4);
            }
            produtoVW.Categorias = _categoriaApp.GetAll().Select(x =>
                                                       new SelectListItem()
                                                       {
                                                           Text = x.Nome,
                                                           Value = x.Id.ToString()
                                                       });

            produtoVW.Fornecedores = _fornecedorApp.GetAll().Select(x =>
                                                    new SelectListItem()
                                                    {
                                                        Text = x.Nomefantasia,
                                                        Value = x.Id.ToString()
                                                    });
            if (Request.IsAjaxRequest())
                return PartialView(produtoVW);
            return View(produtoVW);
        }
        [HttpPost]
        public ActionResult CreateEdit(ProdutoViewModel produtoView )
        {
            HttpPostedFileBase image1 = Request.Files["image1"];
            HttpPostedFileBase image2 = Request.Files["image2"];
            HttpPostedFileBase image3 = Request.Files["image3"];
            HttpPostedFileBase image4 = Request.Files["image4"];
            if (ModelState.IsValid)
            {
                Produto produto;
                if (produtoView.Id == 0)
                {
                    produto = Mapper.Map<ProdutoViewModel, Produto>(produtoView);
                }
                else
                {
                    produto = _produtoApp.GetEntityById(produtoView.Id);
                    produto.CategoriaProdutoId = produtoView.CategoriaProdutoId;
                    produto.Descricao = produtoView.Descricao;
                    produto.Disponivel = produtoView.Disponivel;
                    produto.FornecedorId = produtoView.FornecedorId;

                }

                if (!string.IsNullOrEmpty(image1.FileName))
                {
                    produto.Imagem1 = new byte[image1.ContentLength];
                    image1.InputStream.Read(produto.Imagem1, 0, image1.ContentLength);
                }


                if (!string.IsNullOrEmpty(image2.FileName))
                {
                    produto.Imagem2 = new byte[image2.ContentLength];
                    image2.InputStream.Read(produto.Imagem2, 0, image2.ContentLength);
                }


                if (!string.IsNullOrEmpty(image3.FileName))
                {
                    produto.Imagem3 = new byte[image3.ContentLength];
                    image3.InputStream.Read(produto.Imagem3, 0, image3.ContentLength);
                }


                if (!string.IsNullOrEmpty(image4.FileName))
                {
                    produto.Imagem4 = new byte[image4.ContentLength];
                    image4.InputStream.Read(produto.Imagem4, 0, image4.ContentLength);
                }


                if (produtoView.Id == 0)
                {
                    _produtoApp.AddEntity(produto);
                }
                else
                {
                    _produtoApp.UpdateEntity(produto);
                }

                return RedirectToAction("Index");
            }
            return View(produtoView);
        }

        public ActionResult Delete(int id)
        {
            _produtoApp.DeleteEntity(_produtoApp.GetEntityById(id));
            return Json(new { status = "deletado", JsonRequestBehavior.AllowGet });
        }
    }
}

ECOM.Web/Views/Produto/Index.cshtml
@model List<ECOM.Web.ViewModels.ProdutoViewModel>

<div class="row wrapper border-bottom white-bg page-heading animated fadeInDown">
    <div class="col-sm-4">
        <h2>Cadastro Produto </h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Produto</strong>
            </li>
        </ol>
    </div>
</div>

@Html.Partial("_Result")

ECOM.Web/Views/Produto/_Result.cshtml
@model List<ECOM.Web.ViewModels.ProdutoViewModel>
<div class="wrapper wrapper-content animated fadeInDown">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>
                        <i class="fa fa-list"></i>
                        Produto
                    </h5>
                    <div class="ibox-tools">
                        <button type="button" class="btn btn-success btn-xs" title="Novo" onclick="location.href='@Url.Action("CreateEdit", "Produto")'"><i class="fa fa-plus"></i> Novo</button>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="fullscreen-link">
                            <i class="fa fa-expand"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table id="table-prod" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="width-20">Id</th>
                                <th>Nome</th>
                                <th>Disponivel</th>
                                <th>Descrição</th>
                                <th>Categoria</th>
                                <th>Fornecedor</th>
                                <th class="no-sort width-80">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Nome</td>
                                    <td>@item.Disponivel</td>
                                    <td>@item.Descricao</td>
                                    <td>@item.CategoriaProduto.Nome</td>
                                    <td>@item.Fornecedor.Nomefantasia</td>
                                    <td class="center">
                                        <div class="btn-group">
                                            <a class="btn btn-white btn-xs" accesskey="e" title="Edit" href="@Url.Action("CreateEdit" , "Produto" , new { id = item.Id})"><i class="fa fa-pencil"></i></a>
                                            <button class="btn btn-white btn-xs" accesskey="d" title="Delete" type="button" onclick="Delete('@item.Id')"><i class="fa fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        OFrame.ECOM.Table.GetDefault("#table-prod");
    });

      function Delete(id) {
        var param = { id: id }

        OFrame.ECOM.ConfirmMessage("warning", "@Html.Raw("Dados Serão deletados")", "@Html.Raw("Confirma exclusão")",

            function () {

                $.ajax({
                    type: "Post",
                    contentType: "application/json; charset=utf-8",
                    url: "Produto/Delete",
                    data: JSON.stringify(param),
                    dataType: "json",
                    success: function (data) {
                        OFrame.ECOM.ShowMessage("success", "@Html.Raw("Sucesso")",
                            "@Html.Raw("Deletado")", function () {
                                OFrame.ECOM.OpenAjaxUrl("@Url.Action("Index")");
                            });
                    }
                });
            }
            );
    }

</script>